### ISSUE TITLE
Poseidon operations

### ISSUE THREAD

**Issue by aagi-girish** [poseidonos/poseidonos-gui#1]
Hi,
We are trying to add the GUI to the Poseidon NVMe pool. Please see the next comment for the error info.

Thanks,
Aagi

**Comment by aagi-girish** [comment]
The GUI shows success but the poseidonOS service is not running. Pictures attached. Confirming that IP is added in GO and pos.conf->fe_qos is set to true. The poseidon bin directory is kept in /root/workspace/ibofos/
![image](https://user-images.githubusercontent.com/80010347/140235496-25cb038a-662f-4271-8898-a35a3d3daeab.png)
![image](https://user-images.githubusercontent.com/80010347/140235566-c8068e57-718c-44ce-8835-bf9d52e55680.png)

**Comment by aagi-girish** [comment]
Hi,
Confirming that the poseidonOS is running in the background and the NVMe RAID 5 pool is exposed via TCP. But the GUI still shows not running.
![successfully_running](https://user-images.githubusercontent.com/80010347/141918435-486ba1d3-1423-4c79-8b7a-
26a8ce3a06ec.png)

**Comment by aagi-girish** [comment]
![successfully_running](https://user-images.githubusercontent.com/80010347/141919513-148e0657-fa2e-4bba-afff-0d4451d1f312.png)

**Comment by poseidonssir** [comment]
Hello, thanks for the details and our apology for the delay. We did some more research on this issue and came up with following 2 things that can be tried:

1. 
The setup_env.sh is required to be in a certain sequence for the POS service to be registered properly. The sequence below will make sure the POS is registered correctly.

1. Stop POS from GUI (admin => Poseidon Operations)
2. Run setup_env.sh script 
3. Start POS from GUI 

2.
If you are using an older version of POS, then please update to newer version that is available in https://github.com/poseidonos/poseidonos

Please share the POS version number by running this command:

root@R2U14-PSD-3:/poseidonos/bin# ./poseidonos-cli system info
pos-0.9.10

**Comment by aagi-girish** [comment]
Confirming that the version is the latest. We still have the GUI showing "not running" though the service is actually running in the background.

![image](https://user-images.githubusercontent.com/80010347/145313628-5c0ec904-5504-4af8-9300-fdc4c2269610.png)

![image](https://user-images.githubusercontent.com/80010347/145313579-855bdad0-7672-407b-a279-8a9b808a90e6.png)

**Comment by aswinssir** [comment]
This issue is fixed in the latest version of POS and GUI
