### ISSUE TITLE
Difficult to find the command set D-Agent provides

### ISSUE THREAD

**Issue by mjlee34** [poseidonos/poseidonos-gui#7]
It doesn't seem easy to find the command set D-Agent provides.
I tried some links but could not find the command list. 

How about adding a link to the command list at the initial section of README.md?

It will help the readers easily learn how to access PoseidonOS via REST API.

**Comment by aswinssir** [comment]
The REST API documentation is present in https://github.com/poseidonos/poseidonos-gui/blob/main/src/dagent/doc/api.md.
Thanks for pointing out the difficulty in accessing it. We will update it in the main README.md

**Comment by aswinssir** [comment]
The Readme is updated with the link to REST API document. Please let us know if that looks fine

**Comment by aswinssir** [comment]
Closing the issue as the document has been updated already
