### ISSUE TITLE
Telemetry documentation or assistance

### ISSUE THREAD

**Issue by neteng1** [poseidonos/poseidonos-gui#96]
For my evaluation, I am trying to get Telemetry working. I appear to have it working to Grafana. 

![image](https://user-images.githubusercontent.com/3988748/207765222-fb47125c-5981-4dc0-ba2d-5a0125ce2549.png)

But, I am trying to get statistics to display on the dashboard. But I get this:

![image](https://user-images.githubusercontent.com/3988748/207765434-aa71d2f5-fe61-42c0-a948-8f0d3441cec0.png)

I am assuming it is because I do not have the Telemetry API configured in the IP section. However if I try using the same IP and port that I am using for Grafana, it says it can not connect to the API. 

![image](https://user-images.githubusercontent.com/3988748/207765803-808cb56e-5028-450a-915f-530ca3c1cf73.png)

I am assuming I may have something configured incorrectly, but there is no instruction in the GUI manual for telemetry as it stands today. If there is some documentation that is available, please point me to it. Or provide some guidance as to what I am doing wrong. 

Thanks, I really appreciate the assistance.

**Comment by mjlee34** [comment]
Hi, sorry for the late reply. We will get back to you within a few days! 😃

**Comment by manoj22-k** [comment]
Hi @neteng1, 

You might have taken from main branch which is our development branch.
I request you to take from the branch release/v0.16.0 with tag v0.16.0-rc5.

Please reach out here if you face any issue.

Thanks.

**Comment by neteng1** [comment]
@manoj22-k Thank you very much for your response. 

I install v.0.16.0-rc5 as you suggested. I am still seeing the issue of the telemetry configuration does not all for port 9090, like the Grafana does. 

![image](https://user-images.githubusercontent.com/3988748/209901703-53a502f3-17d9-479e-aa1c-9e372432666e.png)

It would help if instructions stated what port number should be used, or at least what it should match in the poseidonos configurations. 

Also, I have the telemetry fields selected, but they do not appear in Grafana, like I had them earlier. The original screen show was reads. I do not see that in the list of metrics like I used to. Is that a POS_Exporter issue?

![image](https://user-images.githubusercontent.com/3988748/209902429-05674c11-3a99-48d2-a70e-fe511e3de30c.png)


 Thank you again!

**Comment by manoj22-k** [comment]
Hi @neteng1, Thank you for your patience.

Please change the job name from "prometheus" to "poseidonos" and then restart prometheus.
![image](https://user-images.githubusercontent.com/111956415/209910001-41819834-8f86-41dd-93d7-5f3fd381a5ce.png)

Hopefully this will resolve your issue.

And thanks for suggesting to document the steps, we will update our documentation file soon.

**Comment by neteng1** [comment]
Thank you for that, I did miss making that change. I did so per your suggestion.

![image](https://user-images.githubusercontent.com/3988748/210025860-f0ae5c1e-7c65-4fd7-acb3-d4e22d6c4e5c.png)

Now here is what I am getting:

1. I still don't see the "read" and "write" statistics in Grafana. 

![image](https://user-images.githubusercontent.com/3988748/210025937-d3edc08e-4716-404e-b8c3-d7b807fabc6a.png)

2. I noticed that telemetry was not running

![image](https://user-images.githubusercontent.com/3988748/210025971-eb78da89-ebcc-4718-bd06-01fe1edd36f0.png)


3. If I try to start it, it presents a popup and a refresh happens, but it still shows not running.

4. So I looked at syslog on the poseidonos server and saw these errors:

![image](https://user-images.githubusercontent.com/3988748/210026161-62f834cc-37cf-4200-935d-128c332a21b0.png)

5. I did a curl localhost:2112/metrics and saw the read and writes

![image](https://user-images.githubusercontent.com/3988748/210026335-1ad9421c-8496-4b98-b056-ce61d057c1e2.png)

6. However, I do not see it looking at port 9100 0r 9090

![image](https://user-images.githubusercontent.com/3988748/210026452-7c1ed03b-2ba7-460e-8189-0572f05fb125.png)

![image](https://user-images.githubusercontent.com/3988748/210026488-000f4deb-2b60-4ee6-b760-9cca8a66edcf.png)

I am not sure if there are any other logs that may help, but wanted to provide as much information as I could. 

Thank you again!

**Comment by aswinssir** [comment]
@neteng1 The prometheus should be configured to scrape from port 2112, as mentioned in the previous comment. Please change the targets in prometheum configuration yaml to localhost:2112.

The flow is:
1. PoseidonOS Exporter exposes the metrics at port localhost:2112
2. Prometheus takes the value from localhost:2112 and inserts in the database.
3. Prometheus exposes the data at port 9090
4. PoseidonOS-GUI queries the data from port 9090

**Comment by neteng1** [comment]
Thank you for that information. That would mean I need to look at Prometheus. Let me do some digging. I appreciate the response.

**Comment by neteng1** [comment]
Okay, sorry I missed that configuration on the attempt using the version you asked me to go to. I had to rebuild poseidonos and forgot that step. I now have the disk statistics populating all the way to Grafana again. Thank you for your assistance on that.

![image](https://user-images.githubusercontent.com/3988748/210154597-ce2fef00-e1d0-41eb-8b79-2a087b739b0e.png)

Now back to the original question I wrote this issue about. I do not get statistics in the dashboard. I am assuming it is because I do not have the Telemetry defined in the Info section of the dashboard. That may be an incorrect assumption, but that is still the case with v0.16.0-rc5. 

![image](https://user-images.githubusercontent.com/3988748/210154693-d038f3c8-be91-4315-97e6-979d33a9a298.png)

As stated before, when I attempt to configure the Telemetry API, I get errors. I tried to put in the same information that I used for Prometheus (10.0.0.248 port 9090), but I get the following error.

![image](https://user-images.githubusercontent.com/3988748/210154741-33c1174c-5713-443a-bf7a-d6dd25464d15.png)

I tried using the other ports that you described in the flow above (the flow was great, I understand a bit better which helps me troubleshoot). I tried 2112, 9090, 9100 (looks to be a output of pos-exporter). but I get the same error. If I use 3500, it take it, but then I get a message that says Telemetry is not running. 

![image](https://user-images.githubusercontent.com/3988748/210154888-847060e9-47bd-497e-80f3-8731205a9bae.png)

Thank you for your patience as I really appreciate the help and would like to see this all functioning.

**Comment by manoj22-k** [comment]
@neteng1, pLease check where prometheus is running.
In the below scenario prometheus is running on port 9090
![image](https://user-images.githubusercontent.com/111956415/210201081-c0162640-c979-428b-8848-075c4998a4a3.png)

**Comment by neteng1** [comment]
I get to that page by using 9090

![image](https://user-images.githubusercontent.com/3988748/210250256-a7ad5c7e-c497-4e5a-9daf-f3543832cdae.png)

**Comment by aswinssir** [comment]
@neteng1 Can you share the version of Prometheus installed in your system. We just wanted to check if some APIs are failing due to version mismatch. We are using version 2.37.0

**Comment by neteng1** [comment]
Looks like I am running 2.1.0+ds. Let me see if I can upgrade to 2.37.0 and get back to you

![image](https://user-images.githubusercontent.com/3988748/210766587-30ab4c39-7ac2-4fc1-ba5c-939689d9650e.png)

**Comment by neteng1** [comment]
@aswinssir, thank you for that information. I upgraded to 2.37.5 which is the LTS version of Prometheus. 

 
![image](https://user-images.githubusercontent.com/3988748/211174151-b4d78cb7-d80a-4d71-b7f6-b84197494617.png)


So I am trying to understand this better, I originally was using poseidonos-gui version 0.16.0-rc3. I upgraded to 0.16.0-rc5 as requested. The dashboard would still not allow me to enter the telemetry configuration of 9090. I then upgraded Prometheus to 2.37.5, which is the LTS version. (I know you said you were using 2.37.0, but I could not find that specific one) and I am now able to configure and see the dashboard. I am not exactly sure why the upgrade of Prometheus would allow me to then configure it. Is the code checking for something specific on port 9090 that it did not see before in the previous version? I could always get to the Prometheus website using 9090 and Grafana could as well. I was wondering why I could not at least configure it in the dashboard. 

Thank you for all of your help. I really appreciate it.

**Comment by aswinssir** [comment]
@neteng1 Good to know that you can see the metrics right now.

We are using a Prometheus API on port 9090 to check for the status of the database. I suspect that the version you used previously might have some difference in the API, and that might be the reason it was not working. Thanks again for trying it out and letting us know of the issue. To address this, we will add the Prometheus version in the documentation.

**Comment by neteng1** [comment]
@aswinssir, @manoj22-k and @mjlee34 thank you for all your help.
